/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI.Children.DaiLog;

import DAO.KhachHangDAO;
import Models.KhachHang;
import UI.Login_KH;
import Utils.MsgBox;
import Utils.Validation;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author huuho
 */
public class DangKy_KHDialog extends javax.swing.JDialog {

    /**
     * Creates new form DangKy_KHDialog
     */
    boolean flagShowPass = true;
    boolean flagShowPass2 = true;
    KhachHangDAO khachHangDAO = new KhachHangDAO();

    public DangKy_KHDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
            this.setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("/icon/icons8-grocery-store-32.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMatkhau = new javax.swing.JPasswordField();
        txtSDT = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        lblViewPass = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        txtXacNhanPass = new javax.swing.JPasswordField();
        btnEye = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtMatkhau.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        txtMatkhau.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMatkhau.setText("Mật Khẩu");
        txtMatkhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 102)));
        txtMatkhau.setEchoChar((char)0);
        txtMatkhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMatkhauFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatkhauFocusLost(evt);
            }
        });

        txtSDT.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        txtSDT.setForeground(new java.awt.Color(51, 51, 51));
        txtSDT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSDT.setText("Tài Khoản");
        txtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 102)));
        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSDTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSDTFocusLost(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("SansSerif", 1, 38)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 102, 102));
        lblLogin.setText("Đăng Ký");

        lblViewPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Closed Eye_15px.png"))); // NOI18N
        lblViewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewPassMouseClicked(evt);
            }
        });

        txtTenKH.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        txtTenKH.setForeground(new java.awt.Color(51, 51, 51));
        txtTenKH.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenKH.setText("Họ Tên");
        txtTenKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 102)));
        txtTenKH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenKHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenKHFocusLost(evt);
            }
        });

        txtGmail.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        txtGmail.setForeground(new java.awt.Color(51, 51, 51));
        txtGmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtGmail.setText("Gmail");
        txtGmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 102)));
        txtGmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGmailFocusLost(evt);
            }
        });

        txtXacNhanPass.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        txtXacNhanPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtXacNhanPass.setText("Mật Khẩu");
        txtXacNhanPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 102)));
        txtXacNhanPass.setEchoChar((char)0);
        txtXacNhanPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtXacNhanPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtXacNhanPassFocusLost(evt);
            }
        });

        btnEye.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Closed Eye_15px.png"))); // NOI18N
        btnEye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEyeMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thoát");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Đăng ký");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtXacNhanPass, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEye, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblLogin)
                        .addComponent(txtSDT)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtMatkhau)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblViewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtTenKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addComponent(txtGmail, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblLogin)
                .addGap(20, 20, 20)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblViewPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtXacNhanPass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusGained
        // TODO add your handling code here:
        if (txtSDT.getText().equals("Tài Khoản")) {
            txtSDT.setText(null);
        }
    }//GEN-LAST:event_txtSDTFocusGained

    private void txtSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusLost
        // TODO add your handling code here:
        if (txtSDT.getText().isEmpty()) {
            txtSDT.setText("Tài Khoản");
        }
    }//GEN-LAST:event_txtSDTFocusLost

    private void txtMatkhauFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatkhauFocusGained
        // TODO add your handling code here:
        if (String.copyValueOf(txtMatkhau.getPassword()).equals("Mật Khẩu")) {
            if (this.flagShowPass) {
                txtMatkhau.setEchoChar('*');
                txtMatkhau.setText(null);
                return;
            }
            txtMatkhau.setText(null);
        }
    }//GEN-LAST:event_txtMatkhauFocusGained

    private void txtMatkhauFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatkhauFocusLost
        // TODO add your handling code here:
        if (String.copyValueOf(txtMatkhau.getPassword()).isEmpty() || String.copyValueOf(txtMatkhau.getPassword()).equals("Mật Khẩu")) {
            txtMatkhau.setEchoChar((char) 0);
            txtMatkhau.setText("Mật Khẩu");
        }
    }//GEN-LAST:event_txtMatkhauFocusLost

    private void lblViewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPassMouseClicked
        // TODO add your handling code here:
        if (flagShowPass) {
            lblViewPass.setIcon(new ImageIcon(getClass().getResource("/icon/eye_15px.png")));
            txtMatkhau.setEchoChar((char) 0);
            this.flagShowPass = false;
        } else {
            lblViewPass.setIcon(new ImageIcon(getClass().getResource("/icon/Closed Eye_15px.png")));
            txtMatkhau.setEchoChar('*');
            this.flagShowPass = true;
        }
    }//GEN-LAST:event_lblViewPassMouseClicked

    private void txtTenKHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenKHFocusGained
        if (txtTenKH.getText().equals("Họ Tên")) {
            txtTenKH.setText(null);
        }
    }//GEN-LAST:event_txtTenKHFocusGained

    private void txtTenKHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenKHFocusLost
        if (txtTenKH.getText().isEmpty()) {
            txtTenKH.setText("Họ Tên");
        }
    }//GEN-LAST:event_txtTenKHFocusLost

    private void txtGmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGmailFocusGained
        if (txtGmail.getText().equals("Gmail")) {
            txtGmail.setText(null);
        }
    }//GEN-LAST:event_txtGmailFocusGained

    private void txtGmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGmailFocusLost
        if (txtGmail.getText().isEmpty()) {
            txtGmail.setText("Gmail");
        }
    }//GEN-LAST:event_txtGmailFocusLost

    private void txtXacNhanPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtXacNhanPassFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXacNhanPassFocusGained

    private void txtXacNhanPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtXacNhanPassFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXacNhanPassFocusLost

    private void btnEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEyeMouseClicked
        if (flagShowPass2) {
            lblViewPass.setIcon(new ImageIcon(getClass().getResource("/icon/eye_15px.png")));
            txtMatkhau.setEchoChar((char) 0);
            this.flagShowPass2 = false;
        } else {
            lblViewPass.setIcon(new ImageIcon(getClass().getResource("/icon/Closed Eye_15px.png")));
            txtMatkhau.setEchoChar('*');
            this.flagShowPass2 = true;
        }
    }//GEN-LAST:event_btnEyeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Login_KH login = new Login_KH();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        insertKH();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKy_KHDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKy_KHDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKy_KHDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKy_KHDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangKy_KHDialog dialog = new DangKy_KHDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEye;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblViewPass;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JPasswordField txtMatkhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JPasswordField txtXacNhanPass;
    // End of variables declaration//GEN-END:variables
    private boolean validateKH() {
        if (txtSDT.getText().trim().isEmpty() || txtSDT.getText().equals("Tài Khoản")) {
            MsgBox.alert(this, "Vui lòng nhập Số Điện Thoại");
            txtSDT.requestFocus();
            return false;
        }
        if (String.copyValueOf(txtMatkhau.getPassword()).trim().isEmpty() || String.copyValueOf(txtMatkhau.getPassword()).equals("Mật Khẩu")) {
            MsgBox.alert(this, "Vui lòng nhập Mật Khẩu");
            txtMatkhau.requestFocus();
            return false;
        }
        if (txtTenKH.getText().trim().isEmpty() || txtTenKH.getText().equals("Họ Tên")) {
            MsgBox.alert(this, "Vui lòng nhập Họ Tên");
            txtTenKH.requestFocus();
            return false;
        }
        if (txtGmail.getText().trim().isEmpty() || txtGmail.getText().equals("Gmail")) {
            MsgBox.alert(this, "Vui lòng nhập Gmail");
            txtGmail.requestFocus();
            return false;
        }

        if (!txtMatkhau.getText().equals(txtXacNhanPass.getText())) {
            MsgBox.alert(this, "Xác nhận mật khẩu không trùng nhau !");
            return false;
        }
        return true;
    }

    private void clearFormKH() {
        txtSDT.setText("Tài Khoản");
        txtSDT.requestFocus();
        txtTenKH.setText("Họ Tên");
        txtGmail.setText("Gmail");
        txtMatkhau.setEchoChar((char) 0);
        txtMatkhau.setText("Mật Khẩu");
    }

    private void insertKH() {
        if (validateKH()) {
            if (khachHangDAO.selectbyID(txtSDT.getText()) == null) {
                KhachHang khachHang = new KhachHang(txtSDT.getText(), txtTenKH.getText(), 0, txtGmail.getText(), String.copyValueOf(txtMatkhau.getPassword()));
                khachHangDAO.insert(khachHang);
                clearFormKH();
                MsgBox.alert(this, "Thêm Khách Hàng Thành Công");
            } else {
                MsgBox.alert(this, "Số Điện Thoại Này Đã Tồn Tại Trên Hệ Thống");
            }
        }
    }
}
